### ISSUE TITLE
Insertions called as "+N" instead of the corresponding nucleotide

### ISSUE THREAD

**Issue by GaloGS** [andersen-lab/ivar#45] opened 2020-05-05 10:15 UTC
I observed that **some** insertions in .tsv files (called as "+T" in this example), in consensus files appear as "+N". This happens even if providing the reference genome to mpileup. The command line I used with ivar 1.2:
```bash
samtools mpileup -aa -A --reference Sars-Cov-2_REFERENCE.fasta -d 0 -B -Q 0 COV000517.trim.sort.bam | ivar consensus -p COV000517 -q 20 -t 0.7 -m 30 -n N
```
I thought that maybe it could be related to low depths, so I repeated using `-` as low-depth character but again, a +N appeared.

I thought that maybe it could be related to quality filters, so I repeated setting `-q 0` and then something even funnier happened: this and other indels disappeared. 
I attach an image of the consensus genomes obtained with the different options used:

![ivarBug](https://user-images.githubusercontent.com/7755357/81055453-fbf59300-8ec8-11ea-9b45-b292d1f2370a.png)

The .tsv file for that position using our `ivar variants` parameters (`-q 20 -t 0.05 -m 20`):
```
MN908947.3      9604    A       +T      2608    973     67      1313    0       20      0.277766        4727    
```

And for (`-q 0 -t 0`):
```
MN908947.3      9604    A       T       4718    2355    37      8       4       36      0.00169241      4727
MN908947.3      9604    A       C       4718    2355    37      1       1       0       0.000211551     4727
MN908947.3      9604    A       +T      4718    2355    37      1313    0       0       0.277766        4727
```

**Comment by GaloGS** [comment] 2020-05-05 10:17
Also note that the frequencies calculated at that position would be:
0.277 + 0.0002 + 0.002 + REF (0.551)  = 0.83
Therefore there is a remaining 13% that I do not know where it is.

**Comment by gkarthik** [comment] 2020-05-05 17:30
The frequency of the +T is based on the insertion position.

So at pos 9604, the alleles are,

```
T -> 0.00169
C -> 0.000211551
A -> 4718/4727 = 0.998
```

Of the bases in position 9604, the insertion is present in 0.277 of these. 

When you're calling the consensus, the threshold you set is 0.7 and the allele frequencies in that position with the set thresholds are A (2608/4727 = 0.55) and +T (1313/4727 = 0.27).

Since the threshold is 0.7, the consensus is called as AN since the +T is only present at 0.27, the rest are essentially gaps and the consensus between a nucleotide and a gap is `N`. 

Hope this helps!

**Comment by GaloGS** [comment] 2020-05-06 07:33
Now I see why I have +N in my consensus, it makes sense, thank you very much.

Following the frequencies question, are the frequency of the variants calculated on the basis of the total depth of the position? or are they calculated on the basis of the rest of alleles observed with the thresholds set?

Because it is counterintuitive to me to say "the allele frequencies in that position with the set thresholds are A (2608/4727 = 0.55) and +T (1313/4727 = 0.27)." That would rather fit the description that 55% of bases had an A AND pass the thresholds. However, with a set of quality thresholds, if you are only calling A at that position (and not observing any other allele) the frequency should be 100%. Am I correct?

**Comment by paulstretenowich** [comment] 2020-09-28 21:36
Hi,

I'm also facing this issue for samples having an indel with low support. I generate the tsv for variant with a threshold of 25% to keep track of minor variants but I want to create high confidence consensus with a threshold of 75%.
For example I have the following variant computed with `-m 10 -q 20 -t 0.25`:
`MN908947.3      21270   A       +T      6       1       61      4       0       20      0.4     10      0.0541796`
And in my consensus (computed with `-q 20 -t 0.75 -m 10`) I have instead of `A` the insertion `AN`.
Is there a way to exclude completely the insertion instead of writing `N`?

Thanks,
Paul

**Comment by gkarthik** [comment] 2020-09-28 21:47
@paulstretenowich could you please send me the output of `ivar variants -q 0 -t 0` for all nucleotides at that position? Based on the line you sent, +T is a minor variant and should not be in the consensus sequence.

**Comment by paulstretenowich** [comment] 2020-09-28 22:11
@gkarthik after checking there is only the variant I pasted at this position.

**Comment by gkarthik** [comment] 2020-09-28 22:18
Ah okay. So position 21270 basically has the following alleles,
| Allele | Frequency|
|:--|:--|
| A | 0.6 |
| AT | 0.4 | 

The minimum frequency threshold for consensus you have set is `0.75` but neither of these alleles exceed that minimum frequency. So, the final consensus call combined both these alleles to get AN. The `N` is because only one allele has the insertion. You could reduce the threshold to `0.5` to get only `A` or increase the minimum depth to above 10.

**Comment by paulstretenowich** [comment] 2020-09-28 22:46
Yes the position 21270 has A in the reference and in the reads there is an insertion of T, with a support of 40%.
Trying to reduce the threshold from 75% to 50% transforms the `AN` into `AT` but I want to have `A` alone as I want only the high confidence variants, above 75% so discarding the indel for the consensus.

**Comment by gkarthik** [comment] 2020-09-28 23:19
If the threshold is `0.5` then only an `A` should be called at that position since the frequency is 0.6 🤔 . Could you try using `-t 0` during consensus call in which case only the majority allele or in this case an `A` should be part of the consensus. 

Could yo please also confirm that the `AT` is indeed an insertion and not because of the next position being a `T`?

**Comment by paulstretenowich** [comment] 2020-09-29 16:47
After testing again here is the summary. I have a homemade script to show the variant in the ref vs in the consensus and I checked the length of the consensus with a `wc`.

**Comment by gkarthik** [comment] 2020-09-29 21:56
@paulstretenowich this is indeed strange. I was unable to reproduce this particular issue. Is there any chance you could share the mpileup output for position 21270? If required we can also do this over email. My email id is gkarthik[at]scripps.edu. Thank you!

**Comment by gkarthik** [comment] 2020-10-14 23:29
Resolved over email. An edge case caused in homopolymer region with `depth == 10`. Should be resolved by increasing the minimum depth threshold. Thanks all!

**Closed by gkarthik** 2020-10-14 23:29 UTC

**Comment by mbourgey** [comment] 2020-10-21 18:07
Hi,

would it be possible to create on option in order to not include the +N when indels are not called due to read support frequency? 

Otherwise the way the variant are reported between the variant txt file and the consensus is not concordant which may be very misleading.

Thank you

**Comment by gkarthik** [comment] 2020-10-21 18:42
Hello, insertions will not be added if the variant without any insertion is above the specified threshold. Insertion is only added if it needs to be taken into account to go above the threshold. 

For example,

If a position has the following depths,

```
A -> 5
AT -> 3
T -> 2
```

The consensus will be A if the threshold is <= 0.5. If 0.8 >= threshold > 0.5, then AN will be called because the consensus takes A and AT into account. If the threshold is > 0.8 then WN is called. 

Just so I understand, in this case, are you suggesting that we call WT as the variant? This might be problematic since the T is clearly not the majority allele 🤔

**Comment by pphector** [comment] 2020-10-21 19:37
Hi, I think the suggestion is related to the middle case you propose: 

"If 0.8 >= threshold > 0.5, then AN will be called because the consensus takes A and AT into account." 

Is there a way in this case for the consensus to just default back to WT? The issue is that a "masked" insertion is still an insertion in the consensus. For some variant annotators, there is a frameshift introduced, even if the variant is not actually the majority allele. 

What we would like to have is an option that, unless it meets the frequency threshold, no insertion is introduced into the consensus, masked or not. 

Is this possible?

**Comment by gkarthik** [comment] 2020-10-22 00:14
Ah I see you point. It is possible to add a minimum insertion frequency. I created an issue https://github.com/andersen-lab/ivar/issues/79 for this. 
We are currently working through another issues but we will get to this after we're done with those changes.
