### ISSUE TITLE
ivar trim does not work correctly for overlapping pairs

### ISSUE THREAD

**Issue by jts** [andersen-lab/ivar#72] opened 2020-09-23 23:22 UTC
**Describe the bug**

We have observed that `ivar trim` may miss primers when the two halves of a paired end read overlap. This can happen in tagmentation sequencing protocols, like nextera.

**To Reproduce**

Here is a minimal synthetic example that replicates the behaviour we see on real sequencing data:

```
>read/1
CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT
>read/2
ATGTTGACGTGCCTCTGATAAGACCTCCTCCACGGAGTCTCCAAAGCCACGTACGAGCACGTCGCGAACCTGTAAAACAG
```

These reads perfectly overlap - both reads start in ARTIC V3 primer 2_LEFT and end in primer 1_RIGHT. If the reads are mapped as a pair (`bwa mem -p`) then passed to `ivar trim`, only one of the two primer sequences are trimmed from each read (and the trimmed segments don't look correct):

```
read    97      MN908947.3      343     60      64S16M  =       321     80      CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT
read    145     MN908947.3      378     60      8M72S   =       321     -80     CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT
```

If the `-p` flag is omitted, so the reads are unpaired and treated independently, both primers are trimmed from each read:

```
read    0       MN908947.3      343     60      22S43M15S       *       0       0       CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT
read    16      MN908947.3      343     60      22S43M15S       *       0       0       CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT
```

This is the expected behaviour, regardless of whether the reads are paired or not.

**Comment by gkarthik** [comment] 2020-09-24 18:40
Hello! The strand is taken into account while doing the trimming so forward primers are trimmed only from forward strand and reverse primers are trimmed from reverse strand. Isn't this the expected behavior during the trimming step?

**Comment by jts** [comment] 2020-09-24 19:27
I'm not sure I understand - if its a strand issue shouldn't I get the same results when the reads are paired or not?

**Comment by jts** [comment] 2020-09-24 19:39
To be clear the reads are structured like this:

```
r1(fwd) 2_LEFT---------SEQUENCE---------1_RIGHT
r2(rev) 2_LEFT---------SEQUENCE---------1_RIGHT
```

As each read contains two primers, I'd expect both primers to be trimmed:

```
r1(fwd) ---------SEQUENCE---------
r2(rev) ---------SEQUENCE---------
```

If strand is taken into account you'd get:

```
r1(fwd) 2_LEFT---------SEQUENCE---------
r2(rev)       ---------SEQUENCE---------1_RIGHT
```

This would leave primers in the reads and cause issues during variant calling

**Comment by gkarthik** [comment] 2020-09-24 20:48
Wouldn't the overlapping primers to part of two pools? So the only way you would get reads from primers of two different amplicons would be due to minimal contamination in which case the read length should be low. 

However, a quick way to fix this would be remove the last two columns in the BED file (as shown below) in which case iVar will ignore the strand and it should print a message to stdout. 

```
NC_045512.2	30	54	nCoV-2019_1_LEFT
NC_045512.2	320	342	nCoV-2019_2_LEFT
NC_045512.2	385	410	nCoV-2019_1_RIGHT
NC_045512.2	642	664	nCoV-2019_3_LEFT
NC_045512.2	704	726	nCoV-2019_2_RIGHT
NC_045512.2	943	965	nCoV-2019_4_LEFT
```
Please let me know if this works.

**Comment by jts** [comment] 2020-09-24 20:57
Thanks, I tried to remove the strand information and get this result:

When reads are paired (`bwa mem -p`):

```
read    97      MN908947.3      343     60      22S58M  =       321     80      CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT        
read    145     MN908947.3      321     60      65M15S  =       321     -80     CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT        
```

when reads are not paired:

```
read    0       MN908947.3      343     60      22S43M15S       *       0       0       CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT       
read    16      MN908947.3      343     60      22S43M15S       *       0       0       CTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACAT        
```

I believe the issue is that when the amplicons are fragmented by nextera it is ambiguous which amplicon this read belongs to - there is no information that it came from amp1 nor amp2 so the only safe thing to do is trim both adapters, which happens when the reads are unpaired.

**Comment by gkarthik** [comment] 2020-09-24 21:14
Am I reading the second column correctly that based on whether the reads are paired or not they align to different regions of the genome?

Yes, you are correct. This is why the strand comes into account, forward primers are trimmed off only from forward strand and reverse from reverse strand.

**Comment by jts** [comment] 2020-09-24 21:16
The BAM I am showing is after trimming so the start positions shift depending on whether the prefix was trimmed or not. In the untrimmed BAM they align to the same position.

**Comment by jts** [comment] 2020-09-24 21:17
Here's a proposed mechanism for how these reads can be generated:

```
Scenario - Read is from Amplicon2

                              2_LEFT---->
cDNA       -----------------------------------------------------------------
                                                           <----- 2_RIGHT

Amplicon                      2_LEFT------------------------------2_RIGHT


Fragment                      2_LEFT-------------------//-----------2_RIGHT

Sequence                      -------------------------


Scenario - Read is from Amplicon1

1) Amplify
             1_LEFT----->
cDNA       -----------------------------------------------------------------
                                         <----- 1_RIGHT

Amplicon     1_LEFT-----------------------------1_RIGHT

Fragment     1_LEFT---------//--------------------1_RIGHT

Sequence                      ---------------------------

**Comment by gkarthik** [comment] 2020-09-24 21:21
Thank you for illustrating this clearly. So in case 1, the strand of the sequence should be `+`. So iVar will only trim `2_LEFT` and not `1_RIGHT`. In case 2, the strand of the sequence is `-` so iVar will only trim `1_RIGHT` and not `2_LEFT`. Do you think this makes sense? Please let me know if I haven't understood this correctly.

**Comment by jts** [comment] 2020-09-24 21:25
I'm not sure whether you'd only have + reads in scenario 1 and - reads in scenario 2. If that's the case I'd agree these reads could be trimmed correctly. This is a slightly contrived example to illustrate the difference between trimming with and without pairing information, I'll take a look at the real data I have and see what the strands look like.

**Comment by jts** [comment] 2020-09-24 21:33
Ok I refreshed my memory about the real reads that triggered this investigation - the issue is that when you sequence a DNA fragment that is shorter than the read length, you get a read from each strand. So in this case strand information doesn't help resolve the proper way to trim the reads.

**Comment by gkarthik** [comment] 2020-09-24 23:11
Ah I understand. I tried to illustrate this below showing the +ve and -ve strand.

```
                              2_LEFT---->
cDNA       -----------------------------------------------------------------
                                                           <----- 2_RIGHT

Amplicon                      2_LEFT------------------------------2_RIGHT


Fragment                      2_LEFT-------------------//-----------2_RIGHT

Sequence                      //-------------------------2-RIGHT (+)
                                       //-------------------------2-RIGHT (-)
```

Yes, in this case, iVar will miss trimming the 2-RIGHT primer from the forward read. However, looking through some of our data, we see that the vast majority >90% of reads have an insert size greater than 200 so this shouldn't change the consensus. However, this might cause issues for variant calling. So if there is a variant in the primer region, should be worth flagging. Another potential avenue to avoid this would be to add a filter for the insert size 🤔

**Comment by jts** [comment] 2020-09-25 00:21
Yes, I think that's it. I agree that with well behaved data this shouldn't happen often, but certain configurations (2x250bp reads for V3, very short amplicon protocols, overfragmented nextera libraries) it may cause issues. 

For now, I'll probably filter by insert size in the data I have with this issue

**Comment by gkarthik** [comment] 2020-09-25 00:38
Closing this issue in favor of #73. This issue is linked back for future reference. @jts thank you for bringing this to our attention.

**Closed by gkarthik** 2020-09-25 00:38 UTC
